import type { DrawingPackDefinition } from "./types.ts";

export const absurdPack: DrawingPackDefinition = {
  slug: "absurd",
  name: "Absurd",
  icon: "🌀",
  description: "Nonsense, deeply committed to. Good luck drawing these.",
  prompts: [
    "a toaster's retirement party",
    "a cloud with stage fright",
    "a sock puppet uprising",
    "the moon taking a nap",
    "a mailbox that bites",
    "a staircase that goes nowhere",
    "a sandwich running for president",
    "a lamp afraid of the dark",
    "a bicycle with feelings",
    "a tornado made of kittens",
    "a door that refuses to open",
    "a rock with a pet human",
    "a tree growing upside down",
    "a very small elephant in a very big room",
    "a teapot gossiping with a kettle",
    "a volcano erupting glitter",
    "a shoe with a tiny house inside",
    "a chair that hates sitting",
    "a pencil drawing itself",
    "a sneeze that became a cloud",
    "an umbrella that only rains",
    "a candle afraid of fire",
    "a bathtub sailing the ocean",
    "a brick learning to swim",
    "a hat wearing a hat",
    "a mirror with no reflection",
    "a ladder to the moon",
    "a lightbulb with a bright idea",
    "a potato with a passport",
    "a fridge full of snow",
    "a key looking for its lock",
    "a pillow fight between clouds",
    "a spoon that is secretly a fork",
    "a balloon afraid of pins",
    "a sun wearing sunscreen",
    "a hiccup that will not stop",
    "a book reading a person",
    "a car stuck in a jar",
    "a garden of light bulbs",
    "a snowman in a sauna",
    "a toothbrush on vacation",
    "a clock that runs backwards",
    "a hammer at a job interview",
    "a thunderstorm in a teacup",
    "a vacuum that sucks up the sky",
    "a rug that flies away",
    "a staircase in a hurry",
    "a traffic cone on a date",
    "an alarm clock snoozing itself",
    "a mountain made of pillows",
    "a river of soup",
    "a planet with a mustache",
    "a doorknob with a secret",
    "a houseplant on a treadmill",
    "a sneaker that runs away",
    "a pencil sharpener with an appetite",
    "a phone calling itself",
    "a ghost of a sandwich",
    "a tiny whale in a teacup",
    "a lost shadow",
    "a traffic jam of snails",
    "a zipper that will not zip",
    "a smile without a face",
    "a waterfall going up",
  ],
};
