import type { DrawingPackDefinition } from "./types.ts";

export const animalsPack: DrawingPackDefinition = {
  slug: "animals",
  name: "Animals",
  icon: "🐾",
  description:
    "Critters with problems, hobbies, and questionable life choices.",
  prompts: [
    "a sloth in a hurry",
    "a flamingo standing on two legs for once",
    "a hedgehog giving a hug",
    "a goldfish with a big secret",
    "a llama at the post office",
    "a crab doing yoga",
    "a pigeon with a map",
    "a raccoon at a fancy restaurant",
    "a turtle that lost its shell",
    "a duck wearing rain boots",
    "a bat afraid of the dark",
    "a horse on roller skates",
    "a koala that had too much coffee",
    "a goat eating a trophy",
    "a peacock with a bad hair day",
    "a panda doing karate",
    "a seal balancing a birthday cake",
    "a zebra that lost its stripes",
    "a parrot telling a secret",
    "a moose in a phone booth",
    "a cow jumping on a trampoline",
    "a snake wearing a scarf",
    "a rabbit pulling a magician out of a hat",
    "a lobster in a hot tub",
    "a crocodile brushing its teeth",
    "a sheep counting people",
    "a hippo in a tutu",
    "a woodpecker with a headache",
    "a deer caught in the headlights",
    "a pig that loves mud baths",
    "a mole wearing sunglasses",
    "a jellyfish at a disco",
    "a gorilla playing the violin",
    "a starfish sunbathing",
    "a fox stealing a pie",
    "a rhino with a tiny umbrella",
    "an ant carrying a sandwich",
    "a chameleon on a plaid blanket",
    "a polar bear with a fan",
    "a dog chasing its own tail",
    "a squid writing a letter",
    "a beaver building a skyscraper",
    "a worm on a fishing trip",
    "a camel with a flat hump",
    "a butterfly with a hangover",
    "a hamster in a space suit",
    "an eagle that is scared of heights",
    "a cat knocking a cup off a table",
    "a skunk at a perfume shop",
    "a puffin wearing a tuxedo",
    "an armadillo rolling downhill",
    "a gecko stuck to a window",
    "a swan in a bubble bath",
    "a narwhal at a sword fight",
    "a spider that is afraid of flies",
    "an otter holding hands",
    "a walrus eating spaghetti",
    "a ladybug counting its spots",
    "a dog in a sweater",
    "a lion that lost its roar",
    "a cheetah stuck in slow motion",
    "a squirrel with a parachute",
    "a whale singing opera",
    "a mosquito on a diet",
  ],
};
