import type { DrawingPackDefinition } from "./types.ts";

export const classicsPack: DrawingPackDefinition = {
  slug: "classics",
  name: "Classics",
  icon: "🎨",
  description: "A little of everything — the crowd-pleasing mixed bag.",
  prompts: [
    "a cat filing its taxes",
    "a snowman at the beach",
    "a robot learning to dance",
    "a pirate afraid of water",
    "a haunted vending machine",
    "a dog driving a bus",
    "a very tired superhero",
    "a cactus that wants a hug",
    "a volcano with a cold",
    "a knight fighting a vacuum cleaner",
    "a banana on vacation",
    "an octopus doing the dishes",
    "a ghost trying on hats",
    "a lighthouse in love",
    "a penguin at a job interview",
    "a pizza delivery by helicopter",
    "a moon eating a cookie",
    "a giraffe in a tiny car",
    "a nervous skydiver",
    "a tree getting a haircut",
    "an alien at the dentist",
    "a grumpy cloud",
    "a snail winning a race",
    "a wizard stuck in traffic",
    "a shark at a birthday party",
    "a sandcastle with a moat monster",
    "a traffic light having a bad day",
    "a chicken crossing a very busy road",
    "a bear riding a unicycle",
    "a rainbow made of socks",
    "an umbrella in a hurricane",
    "a dragon toasting marshmallows",
    "a spider knitting a scarf",
    "a sunflower wearing sunglasses",
    "a camel at the north pole",
    "a hamster running a marathon",
    "a mermaid at the gym",
    "a castle made of pancakes",
    "a frog with a jetpack",
    "a clock that is always late",
    "a baby elephant taking a bath",
    "a lonely sock in the dryer",
    "a kite stuck in a tree",
    "a squirrel hoarding phones",
    "a teapot having a tantrum",
    "a whale in a bathtub",
    "a hot air balloon made of bubblegum",
    "a mouse lifting weights",
    "a snowflake on a sunny day",
    "a scarecrow that loves crows",
    "an owl reading the news",
    "a cowboy riding a turtle",
    "a flower growing out of a boot",
    "a submarine full of fish tourists",
    "a kangaroo with an overstuffed pouch",
    "a sleepy alarm clock",
    "a pumpkin going to prom",
    "a bee with a tiny briefcase",
    "a caveman discovering wifi",
    "a lion at the hair salon",
    "a paper airplane on a long trip",
    "a worm wearing a top hat",
    "a mountain climbing a person",
    "a birthday cake on fire",
  ],
};
