import type { DrawingPackDefinition } from "./types.ts";

export const fantasyPack: DrawingPackDefinition = {
  slug: "fantasy",
  name: "Fantasy",
  icon: "🐉",
  description: "Dragons, wizards, and quests with slightly lower stakes.",
  prompts: [
    "a dragon hoarding rubber ducks",
    "a wizard whose spell went wrong",
    "a unicorn stuck in traffic",
    "a troll collecting tolls on a tiny bridge",
    "a fairy with a broken wing",
    "a knight who is afraid of horses",
    "a potion that turns you into a frog",
    "a castle in the clouds",
    "a goblin selling used swords",
    "a mermaid king with a fork",
    "a phoenix rising from a toaster",
    "a giant who is very gentle",
    "an elf making toys",
    "a talking sword",
    "a magic mirror that is too honest",
    "a witch on a vacuum cleaner",
    "a centaur trying on jeans",
    "a treasure chest with teeth",
    "a crystal ball showing the weather",
    "a haunted suit of armor",
    "a sea serpent in a bathtub",
    "a griffin at the vet",
    "a spellbook with a bookmark",
    "a gnome in a garden",
    "a pegasus with a flat tire",
    "a dwarf mining for candy",
    "a wand that only makes bubbles",
    "an enchanted forest with angry trees",
    "a cyclops with a monocle",
    "a sphinx asking a silly riddle",
    "a kraken attacking a rubber boat",
    "a genie coming out of a teapot",
    "a hydra at the hairdresser",
    "a vampire at the blood bank",
    "a werewolf at the groomer",
    "a mage casting a snack spell",
    "a quest for the golden spoon",
    "a dragon egg hatching",
    "a flying broom race",
    "a tower with no door",
    "a prince turned into a teapot",
    "a magic bean growing a beanstalk",
    "a fire breathing chicken",
    "a sword stuck in a stone",
    "a ghost ship in a bottle",
    "a mushroom village",
    "a portal to a laundry room",
    "an ice queen with a runny nose",
    "a pixie riding a dragonfly",
    "an orc at a tea party",
    "a spell scroll that is too long",
    "a golem made of cookies",
    "a basilisk wearing sunglasses",
    "a crown too heavy to wear",
    "a moon goddess changing a light bulb",
    "a map to nowhere",
    "a knight in shining pajamas",
    "a bard with a broken lute",
    "a dragon dentist",
    "a wishing well full of complaints",
    "a skeleton warrior at a dance",
    "a flying island",
    "a baby dragon learning to fly",
    "a wizard hat with a rabbit living in it",
  ],
};
