import type { DrawingPackDefinition } from "./types.ts";

export const foodPack: DrawingPackDefinition = {
  slug: "food",
  name: "Food",
  icon: "🍕",
  description: "Snacks with feelings and meals gone wrong.",
  prompts: [
    "a broccoli bodybuilder",
    "a donut going for a swim",
    "a sandwich too tall to eat",
    "a sad lonely pea",
    "a carrot at the eye doctor",
    "an egg afraid of the frying pan",
    "a hot dog in a sleeping bag",
    "a pineapple at the barber",
    "a spaghetti monster",
    "a taco falling apart",
    "a cupcake with a birthday wish",
    "a potato watching television",
    "a burger with too many layers",
    "an onion that makes everyone cry",
    "a lemon making a sour face",
    "a waffle with a bad sunburn",
    "a cookie hiding from a glass of milk",
    "a pickle in a suit",
    "an ice cream cone melting in the sun",
    "a banana slipping on a person",
    "a toaster launching toast into space",
    "a cheese with too many holes",
    "a coconut that fell on someone",
    "a popcorn kernel about to pop",
    "a strawberry wearing a crown",
    "a soup with a fly in it",
    "a pretzel doing yoga",
    "a watermelon rolling downhill",
    "a sushi roll surfing",
    "a mushroom umbrella",
    "a chili pepper breathing fire",
    "a muffin with a mustache",
    "a stack of pancakes toppling over",
    "a grape that became a raisin",
    "a corn cob playing the harmonica",
    "a cake that is a little too honest",
    "a meatball rolling off the table",
    "an avocado doing sit ups",
    "a bowl of cereal at the beach",
    "a jelly bean in a dance battle",
    "a garlic clove scaring away a vampire",
    "a lollipop that never ends",
    "a peanut in a spacesuit",
    "an apple with a worm roommate",
    "a baguette used as a sword",
    "a teacup with a tiny storm inside",
    "a french fry lifeguard",
    "a salad nobody ordered",
    "a gingerbread man running away",
    "a milkshake with too many straws",
    "a fortune cookie with bad news",
    "a tomato refusing to become ketchup",
    "a blender at a rock concert",
    "a candy cane on vacation",
    "a burrito wearing a blanket",
    "a cherry on top of a mountain",
    "a lunchbox full of surprises",
    "a noodle in a tangle",
    "a hot pepper at the ice rink",
    "a chocolate bar in a heat wave",
    "a pie in the face",
    "a pear doing ballet",
    "a food truck chase",
    "a bagel that became a donut",
  ],
};
