import type { DrawingPackDefinition } from "./types.ts";

// Scenes and tropes, never titles — nothing here is anyone's trademark, and
// a description is more fun to draw (and to bluff) than a name.
export const moviesPack: DrawingPackDefinition = {
  slug: "movies",
  name: "Movies & TV",
  icon: "🎬",
  description: "Famous scenes and tropes, described instead of named.",
  prompts: [
    "a shark that is afraid of water",
    "a hero walking away from an explosion",
    "a detective with a giant magnifying glass",
    "a spaceship landing on a farm",
    "a haunted house with a friendly ghost",
    "a cowboy showdown at noon",
    "a robot falling in love",
    "a giant ape on a skyscraper",
    "a car chase with shopping carts",
    "a wizard school sorting hat",
    "a treasure map with a big red X",
    "a dinosaur in a theme park",
    "a time machine made from a car",
    "a talking snowman in summer",
    "a boy who flies away on a bicycle",
    "a ship hitting an iceberg",
    "a superhero doing laundry",
    "a zombie at a job interview",
    "a news anchor in a hurricane",
    "a game show with a big spinning wheel",
    "a talent show judge falling asleep",
    "a villain with a fluffy white cat",
    "a spy hanging from the ceiling",
    "a mummy that unraveled",
    "a king without a castle",
    "a monster under the bed",
    "a clown in a storm drain",
    "a secret agent in a tuxedo",
    "a lost fish looking for its dad",
    "an ogre living in a swamp",
    "a kid home alone with traps everywhere",
    "a boxer running up the stairs",
    "a princess kissing a frog",
    "a giant marshmallow man",
    "a ghost hunter with a vacuum pack",
    "a toy cowboy and a space ranger",
    "a lion cub held up on a cliff",
    "a pirate ship with black sails",
    "a car that turns into a robot",
    "a cooking show disaster",
    "a sitcom couch with a laugh track",
    "a soap opera slap",
    "an alien phoning home",
    "a hobbit on a long walk",
    "a nature documentary about a houseplant",
    "a magic carpet ride",
    "a family of superheroes at dinner",
    "a snowy hotel with a creepy hallway",
    "a mermaid trading her voice",
    "a detective in a deerstalker hat",
    "a western saloon brawl",
    "a monster truck rally",
    "a courtroom drama with a surprise witness",
    "a heist through the air vents",
    "a karate kid balancing on one leg",
    "a cartoon anvil falling",
    "a coyote chasing a very fast bird",
    "a baking contest gone wrong",
    "a reality show on a desert island",
    "a weather reporter blown away",
    "a vampire in the sunlight",
    "a musical number in the rain",
    "a submarine that is yellow",
    "a masked hero on a rooftop",
  ],
};
