import type { DrawingPackDefinition } from "./types.ts";

export const officePack: DrawingPackDefinition = {
  slug: "office",
  name: "Office life",
  icon: "💼",
  description: "Meetings, printers, and the quiet drama of the break room.",
  prompts: [
    "a printer that jams on purpose",
    "a meeting that could have been an email",
    "a coffee machine on strike",
    "a stapler with ambitions",
    "a desk plant that needs a raise",
    "a video call with the camera on by accident",
    "a boss made of sticky notes",
    "an intern carrying twelve coffees",
    "a spreadsheet with feelings",
    "an office chair race",
    "a paperclip giving advice",
    "a fire drill in slippers",
    "a laptop about to die",
    "a microwave with a fish lunch",
    "a to do list that never ends",
    "a whiteboard nobody can erase",
    "an elevator full of awkward silence",
    "an inbox exploding",
    "a keyboard missing the space bar",
    "a mouse on a mousepad",
    "a team building trust fall",
    "a cubicle turned into a fort",
    "a birthday cake for someone nobody knows",
    "a water cooler gossip session",
    "a monday morning alarm",
    "a friday at five pm",
    "a pie chart that is actually a pie",
    "a password written on a sticky note",
    "a shredder eating the wrong document",
    "a promotion ladder",
    "a presentation with too many slides",
    "a snack drawer raid",
    "a phone with a hundred missed calls",
    "a deadline chasing someone",
    "a robot replacing the receptionist",
    "a lunch stolen from the fridge",
    "a desk buried in paperwork",
    "a performance review for a cat",
    "an out of office beach chair",
    "a conference call with a dog barking",
    "a boss on a scooter",
    "a stack of mugs that are all dirty",
    "a copy machine making copies of a face",
    "a motivational poster of a sad cat",
    "a new employee on the first day",
    "a computer taking forever to update",
    "a revolving door trap",
    "a tie that is way too long",
    "a server room on fire",
    "a desk with a hundred monitors",
    "a coffee spill on important papers",
    "a very long commute",
    "a standing desk that will not stop rising",
    "a fax machine in a museum",
    "a raise that is one penny",
    "an office party with one balloon",
    "a hot desk that is actually on fire",
    "a lanyard with too many badges",
    "a brainstorm that is literally a storm",
    "a manager micromanaging an ant",
    "a quarterly report shaped like a mountain",
    "a sticky note covered monitor",
    "a mysterious smell in the break room",
    "a vacation request denied",
  ],
};
